### ISSUE TITLE
Focus moves to other open emacs frame after closing

### ISSUE THREAD

**Issue by nishadsabnis** [alphapapa/yequake#13]
I'm not sure this is an issue with yequake versus being an issue with something else in my config/setup so feel free to tell me so! 

I have an Emacs frame already open in MacOS Space 1(virtual desktop). 
I call yequake-toggle in MacOS Space 2 and the frame shows up as expected. I make the changes I need and call yequake-retoggle to close the new frame. However when I do this the frame closes but then focus switches to the existing emacs frame. (away from virtual desktop currently being used) 
This is not a big problem but since the whole value addition of yequake is to allow you to make changes without switching contexts completely, it would be great if I could just continue working as I never opened the yequake frame.

**Comment by alphapapa** [comment]
Sorry, I don't think I can help you with that.  It might be an issue in MacOS, or an issue in the particular Emacs build you have installed, or a general issue with the way Emacs works when closing a frame, possibly specific to MacOS or possibly on all window systems.  You might be able to determine which it is by looking at the Emacs source code.

If you are able to find a simple workaround, I'll be glad to consider adding it to this package.

**Comment by alphapapa** [comment]
It might also be possible to store the previous window ID and switch back to it after closing the Yequake frame, but that might not always be the desired action, so I'm not sure if it would be a good idea to do that.

**Comment by nishadsabnis** [comment]
Yep thought so, I think it has something to do with MacOS. 
Without using yequake, if I just create two emacs frames and put them on two separate windows, then calling ```delete-frame``` on one of the frames causes focus to shift back to other. Since this is not yequake-specific please feel free to close if you want. I will close it in a few days if I can think of nothing better to try/add here

**Comment by nishadsabnis** [comment]
Closing this since I am not too bothered and the issue does not lie with the package behaviour.

**Comment by alphapapa** [comment]
Thanks.  Please let me know if you find a good workaround that could be documented.

**Comment by jek** [comment]
Solution for me was a MacOS emacs built with `--with-no-frame-refocus`. I built emacs from homebrew to get the flag.
