### ISSUE TITLE
Help defining a `buffer-fn`

### ISSUE THREAD

**Issue by apc** [alphapapa/yequake#19]
I'm trying [again](https://github.com/alphapapa/yequake/issues/18) to get around [this issue](https://github.com/alphapapa/yequake/issues/13). But I need help understanding why the following doesn't work when called via `emacsclient`: 

```
(defun my/yequake-org-capture (&optional goto keys)
  "Call `org-capture' in a Yequake frame.
Adds a function to `org-capture-after-finalize-hook' that closes
the recently toggled Yequake frame and removes itself from the
hook.
Note: if another Yequake frame is toggled before the capture is
finalized, when the capture is finalized, the wrong Yequake frame
will be toggled."
  (let* ((return-to-app (lambda () (shell-command (concat "open -a " my-last-app))))
         (remove-hook-fn (lambda () (setq org-capture-after-finalize-hook nil)))
         )
    (add-hook 'org-capture-after-finalize-hook remove-hook-fn)
    (add-hook 'org-capture-after-finalize-hook return-to-app)
    (add-hook 'org-capture-after-finalize-hook #'yequake-retoggle)
    ;; MAYBE: Propose an `org-capture-switch-buffer-fn' variable that could be rebound here.

    ;; NOTE: We override `org-switch-to-buffer-other-window' because
    ;; it always uses `switch-to-buffer-other-window', and we want to
    ;; display the template menu and capture buffer in the existing
    ;; window rather than splitting the frame.
    (cl-letf* (((symbol-function #'org-switch-to-buffer-other-window)
                (symbol-function #'switch-to-buffer)))
      (condition-case nil
          (progn
            (org-capture goto keys)
            ;; Be sure to return the "CAPTURE-" buffer, which is the current
            ;; buffer at this point.
            (current-buffer))
        ((error quit)
         ;; Capture aborted: remove the hook and hide the capture frame.
         ;; (remove-hook 'org-capture-after-finalize-hook #'yequake-retoggle)
         ;;
         (funcall remove-hook-fn)
         (funcall return-to-app)
         (yequake-retoggle)
         )))))
```

As you can see, this is a simple variation on `yequake-org-capture`. My thought was to add an extra function to `org-capture-after-finalize-hook` that would open the last visited app. The above function does what I want (I think) if I call it from Emacs (removing the calls to `yequake-retoggle`): opens up a capture buffer and after finishing the capture or quitting, I'm sent back to whatever app is set as the value of `my-last-app`. 

But when I try to use that function with `yequake`, things don't quite work as I expect: calling 

```
emacsclient -ne '(yequake-toggle "my/org-capture")' 
```

after adding "my/org-capture" to `yequake-frames` doesn't bring up Emacs to the front. 

This is not so much an issue as a request for help understanding how to build my own `buffer-fns` for use with `yequake-toggle`. Again, if this isn't the best place to raise this question, just let me know etc.

**Comment by apc** [comment]
OK, this seems to be an issue with the Mac Port version of Emacs. I just ran 

```
emacsclient -ne '(yequake-toggle "org-capture")' 
```

using the frame parameters in the README and found the same problem: if Emacs has been *hidden* (using e.g. Cmd + H), as opposed to merely not being the frontmost app, nothing will happen until I Cmd + Tab my way to Emacs. I have no idea why. 

The problem does not arise with the `emacs-plus` version of Emacs. There, I can both call `yequake-toggle` with `org-capture` or with `my/org-capture` and get the desired behavior. (Well, almost: in both cases, calling `yequake-toggle` leads to other open frames showing behind the `yeaquake` frame. But I haven't looked into whether that's the intended behavior or not, and if not, whether there's something else in my config that could be triggering this.)

**Comment by alphapapa** [comment]
Have you concluded whether there is a bug or problem in this package, or whether it's just in that Mac port?  If the latter, please close this issue, but feel free to continue documenting it here for the benefit of other users.  Thanks.

**Comment by apc** [comment]
Thanks. I think it's definitely not a problem with this package. I will close the issue and will document any updates if I get them here.
