### ISSUE TITLE
Using activities.el to persist frame across innovations 

### ISSUE THREAD

**Issue by haji-ali** [alphapapa/yequake#28]
Following on #27, I am trying to use [activites.el](https://github.com/alphapapa/activities.el) for the same purpose as that PR (persist frame across innovations).

I am still learning about the design and functionality of `activites.el`, but to start with I came up with this `yequake--toggle-frame` implementation (just as a way to test how `activites.el` could be called, the implementation is certainly not correct). 

<details>

```
(defun yequake--toggle-frame (name frame)
  "If frame named NAME exists but is unfocused, raise and focus it; if focused, delete it; otherwise, display FRAME anew."
  (let ((activity (map-elt activities-activities name)))
    (if-let* ((visible-frame (alist-get name (make-frame-names-alist) nil nil #'string=)))
        (if (and yequake-focused (equal visible-frame (selected-frame)))
            ;; Frame is visible and focused: delete it.
            (progn (with-selected-frame visible-frame
                     (activities-suspend activity)))
          ;; Frame is visible but not focused: raise and focus it.
          (select-frame-set-input-focus visible-frame)
          (setq yequake-focused t))
      ;; Frame doesn't exist: make it.
      (-let* (((&alist '_x '_y 'width 'height 'left 'top 'buffer-fns 'alpha 'frame-parameters) frame)
              ((monitor-x monitor-y monitor-width monitor-height) (mapcar #'floor (alist-get 'geometry (frame-monitor-attributes))))
              (frame-width (cl-typecase width
                             (integer width)
                             (float (floor (* monitor-width width)))))
              (frame-height (cl-typecase height
                              (integer height)
                              (float (floor (* monitor-height height)))))
              (frame-x (or left
                           (+ monitor-x (floor (/ (- monitor-width frame-width)
                                                  2)))))
              (frame-y (or top monitor-y))
              (new-frame (make-frame (append frame-parameters
                                             (list (cons 'name name)
                                                   (cons 'alpha alpha)
                                                   (cons 'left frame-x)
                                                   (cons 'top frame-y)
                                                   (cons 'width (cons 'text-pixels frame-width))
                                                   (cons 'height (cons 'text-pixels frame-height))
                                                   (cons 'user-position t))))))

        (select-frame new-frame)
        (select-frame-set-input-focus new-frame)
        (if activity
            (let ((activities-resume-into-frame 'current))
              (activities-resume activity))
          (delete-other-windows))
        (add-hook 'focus-in-hook #'yequake--focus-in)
        (add-hook 'focus-out-hook #'yequake--focus-out)
        (setq yequake-recent-frame-name name
              yequake-focused t)
        ;; Call show-buffers function after setting focus and variable.
        ;; If show-buffers is aborted, the frame will be focused and
        ;; recorded as such, so -retoggle can hide it again.  This is
        ;; required for `yequake-org-capture'.
        (unless activity
          (when (yequake--show-buffers buffer-fns)
            new-frame)
          (with-selected-frame new-frame
            (activities-define name)))
        new-frame))))
```
</details>

Here is what I found so far
- I believe yequake is incompatible with activities.el when `activities-tabs-mode` is enabled.
- For some reason, not all frame parameters are saved with `activities.el`, so I have to re-create the frame with all the parameters and call `activities-resume` with the `activities-resume-into-frame` set to `current`.
- `activities.el` doesn't seem to save tabs, just windows. I am mainly interested in saving tabs.
- There is also some extra weirdness (with focus) on my system when toggling yequake off when using `activities.el` vs when not using it, so the previous implementation is not completely side-effect free.

Overall, I am finding it somewhat difficult to get `activities.el` working as I would expect it and the implementation in #27 is much more straightforward.

**Comment by alphapapa** [comment]
Well, the starting point I had in mind was to call `activities-resume` in the Yequake buffer functions, or something like that.  The idea would be that Yequake would open a frame, and Activities would then restore an activity (window configuration) into it.  I would expect there to be details to be worked out, and maybe some changes to be made on both sides to enable better integration, but the idea would be to not make any changes one side that are specific to the other, i.e. generally hooks and such should be used to enable general integration.

If you need Activities to deal with frame parameters, feel free to open an issue on its tracker to discuss it.
