### ISSUE TITLE
lightening repo from images

### ISSUE THREAD

**Issue by szabolcs-szilagyi** [alphapapa/yequake#8]
One could lighten the repository size from the images:
1. upload the images in a issue or comment here in github
2. remove it from the source control
3. in the readme.org link to the image on github

e.g.:
the link to the below image is: https://user-images.githubusercontent.com/2981123/50853141-baf77800-1381-11e9-93b6-87dc4e93d803.png
![dont-tread-on-emacs-150](https://user-images.githubusercontent.com/2981123/50853141-baf77800-1381-11e9-93b6-87dc4e93d803.png)

**Comment by alphapapa** [comment]
I want the images in the repository.  I don't want to have to keep track of them in another location, ensure the links remain valid, etc.  Do you really think 5.7 MB is too big for a git repo on GitHub?  I've cloned much larger ones, and disk space is not at such a premium for anyone anymore.

**Comment by szabolcs-szilagyi** [comment]
If you like to keep the images in one place along the documentation fair enough :smiley: 
Looking at the package done by elpa they are excluded anyway. For me an extra images folder is just noise in the repository, but can understand if you would like to keep it along the documentation.
